### ISSUE TITLE
Breaks with Planet Packs

### ISSUE THREAD

**Issue by BravoAlpha101st** [severedsolo/ExplorationPlus#8]
I made a save to test this mod before I bring it to my other save. It immediately gives me a mission to explore Valentine, a star that is about 11 LIGHT YEARS away from Kerbin. The Planet packs I use are Extrasolar and Outer Planets Mod.

**Comment by severedsolo** [comment]
That's an issue with your planet pack. It uses the stock progression system, which ranks bodies by their science multiplier. If you're being directed to a bad target then the science multiplier needs to be changed.
